const ERROR_VALIDATE = 400;
const ERROR_NOTFOUND = 404;
const ERROR_DEFAULT = 500;
const ERROR_FORBIDDEN = 403;
const ERROR_UNAUTH = 401;
const ERROR_CONFLICT = 409;

module.exports = {
  ERROR_VALIDATE,
  ERROR_NOTFOUND,
  ERROR_DEFAULT,
  ERROR_FORBIDDEN,
  ERROR_UNAUTH,
  ERROR_CONFLICT,
};
